### PR TITLE
textures for all shaders

### PR DESCRIPTION
**Pull request by Grodou**
Texture export for most shaders (not just Principled BSDF)
Texture rotation fix
Rounds floats to avoid 15 decimal numbers (default to 6)

Changes

---------------------------------------------------------
ogre/material_utils.MaterialShader
---------------------------------------------------------
Finds the main shader of a material (connected to the Surface material output)
Provides uniform access to shader's textures and input sockets via keys.
Based on bpy_extras.node_shader_utils.PrincipledBSDFWrapper for node detection and textures
Works for most types of shaders

---------------------------------------------------------
util.IndentedWriter
---------------------------------------------------------
Round method for floats

---------------------------------------------------------
ogre/material
---------------------------------------------------------
Adaptation to MaterialShader.
Rounds float values to avoid 15 decimal numbers
Converts radians to degrees for proper texture rotation
Clean old texture generation method

### CODE REVIEW

**Comment by paroj** [comment]
> Texture export for most shaders (not just Principled BSDF)

while I think this is generally a nice addition, I am hesitant to pull this into blender2ogre for two reasons:
1. It is a lot of blender internal code: as you probably already noticed, we carry quite a lot of dead code with blender2ogre because the people originally written the functionality moved on and I dont have the capacity to test every specific functionality.
Using `PrincipledBSDFWrapper` means that it is maintained by blender and internal API changes will be handled upstream.
2. There is very little benefit for Ogre, as all different BSDF materials are mapped to the same Ogre BSDF (the only one supported). Therefore we can just as well require Principled BSDF within blender, as the result will look slightly different anyway.

I would rather suggest pushing the generalized PrincipledBSDFWrapper to blender directly. Here, I will rather cherry pick the remaining fixes.

**Comment by Grodou** [comment]
Hi,
the jMonkey engine (https://jmonkeyengine.org) relies on Ogre files for mesh and scene imports, especially for textures.
Any jMonkey project initiated before Blender 2.80 would have to choose:
	- keep on using Blender < 2.80
	- replace all shaders with Principled
I agree, embedded modules like PrincipledBSDFWrapper will be maintained.
They can also change and force add-ons to adapt, as the 2.80 version did.

**Comment by paroj** [comment]
are we talking about (1) materials in .blend files or (2) about materials in the engine?

1. you are pretty much screwed up. blender2ogre exported materials based on the blender render pipeline which is now gone. Therefore, you must update your .blend files to use cycles node-based materials. For this you can just pick Principled BSDF.
2. Nothing really changes. The exporter still writes Phong material properties as it did with blender 2.79. Ideally the engine (jmonkey and ogre) would use Principled BSDF shaders to match what you see in blender *exactly*. When allowing the other BSDFs in blender, the engines would need to provide matching shaders for those as well.

**Comment by Grodou** [comment]
It's all about (1) materials in .blend files
I've read some discussions about export design choices on https://developer.blender.org/maniphest.
And as you suggested, if we want to export in Blender 2.8x, the material should have:
- one Principled BSDF node directly connected to the material output
- some texture nodes directly connected to it and/or one texture behind a Normal Map node (Normal slot)
- texture transformations made by Mapping node

Many users complained about that new huge restriction, if they ever find out why it does not work anymore (no feedback at all in the UI).
`MaterialShader` works the same way as `PrincipledBSDFWrapper` for export, except:
- it handles other types of shaders and does not force users to update all their existing .blend files
- if no appropriate shader can be found, it does not create a fake one
I thought it was more handy.

If ogre exporter has to stick to the official restrictions, that's perfectly understandable.
Maybe some kind of information window could be displayed, telling about limitations and how to convert materials for proper export ?

Are the texture rotation and floats rounding useful ? Should I close the PR, create a new one ?

**Comment by paroj** [comment]
> it handles other types of shaders and does not force users to update all their existing .blend files

yeah, thats my point: There should be no existing .blend files with shaders targeting blender2ogre, as we did not support shaders before your first PR.

> Maybe some kind of information window could be displayed, telling about limitations and how to convert materials for proper export ?

I would add that to the README https://github.com/OGRECave/blender2ogre/blob/2.80-support/README.md#blender2ogre
Maybe create a info window suggesting to actually read the README.

> Are the texture rotation and floats rounding useful ? Should I close the PR, create a new one ?

yes, definitely. I just did not get to factor them out yet. If you could do the changes that would help. No need to open a new PR, you can just make the changes (e.g. in a new branch) and then do:

```
git push -f origin/2.80-support
```

to update this PR.

**Comment by Grodou** [comment]
OK, PR updated, `MaterialShader` removed.
Just to be perfectly clear, its goal was to let existing .blender files work as they are, without any update.
Now that it's gone, users must manually edit their old files for correct material exports.

**Comment by paroj** [comment]
> Just to be perfectly clear, its goal was to let existing .blender files work as they are, without any update.

I guess we are still talking past each other. With existing .blender files, you mean arbitrary .blender files created with blender 2.80? I was referring with "existing files" to .blender files created with blender 2.7x and specifically targeted for ogre export.

**Comment by Grodou** [comment]
Yeah, a bit misleading...
By existing .blender files, I mean arbitrary files created with blender 2.7x
That was my case. I opened old 2.7x files with 2.8x, and tried to export.

**Comment by paroj** [comment]
and you were using Cycles Render with Nodes I assume?

**Comment by Grodou** [comment]
Yes I did.

**Comment by paroj** [comment]
ah... I assumed we are talking about 2.7x files that were previously used with blender2ogre master, which would imply "Blender Render".

Of course for converting general blender files, using arbitrary shaders is a thing - but then again they do not map too well to ogre materials right now..

**Comment by Grodou** [comment]
Understood :)
I use ogre exporter for main static scenes (and wavefront for some other meshes), and import them into a jMonkey project.
Materials are correct, no need for more accuracy in my case.

**Pull request merged**
