### PR TITLE
Code clean up

### PR DESCRIPTION
**Pull request by oldmanauz**
1. Created directory called `archived_code` and moved the following files there:
  *ui/materials.py
  *unused.py
  *game_logic.py
  *todo.py
  *terrain.py
2. Removed `OGRETOOLS_MESH_MAGICK` from the preference. This was only used in `todo.py` which is now archived.
3. Renamed `io_ogre/meshy.py` to `io/mesh_preview.py` and updated code references so that it is non specific to a particular external tool.
4. Removed old comments in `ui/__init.py__` > auto_register()

### CODE REVIEW

**Comment by paroj** [comment]
ideally you would rebase your local branch on master instead of merging master. This would allow to preserve your individual commits.

**Comment by oldmanauz** [comment]
@paroj is there some documentation explaining this?

> ideally you would rebase your local branch on master instead of merging master. This would allow to preserve your individual commits.

**Comment by sercero** [comment]
@oldmanauz, I highly recommend that you take a look at these pages to see the best practices that @paroj is recommending:
https://stackoverflow.com/questions/7244321/how-do-i-update-a-github-forked-repository
https://www.atlassian.com/git/tutorials/git-forks-and-upstreams
https://stackoverflow.com/questions/5189560/squash-my-last-x-commits-together-using-git
https://railsware.com/blog/git-housekeeping-tutorial-clean-up-outdated-branches-in-local-and-remote-repositories/
https://www.freecodecamp.org/news/how-to-delete-a-git-branch-both-locally-and-remotely/
https://stackoverflow.blog/2021/04/05/a-look-under-the-hood-how-branches-work-in-git/
https://docs.github.com/en/github/authenticating-to-github/creating-a-personal-access-token

https://kernelnewbies.org/PatchPhilosophy

**Comment by oldmanauz** [comment]
@sercero Thanks.
I did spend a few hours yesterday doing some reading. I think I understand the process a little better and I had to fix my fork repoistory.

**Pull request merged**
